### PR TITLE
closes #153. Handles WOS case when only a single publication.

### LINKED ISSUE #153: no implicit conversion error in wos_to_sparql_statements
Steps to reproduce:
1. `exe/publications load -i researchers_sample.csv`

Expected result:
Publications are extracted, transformed, and loaded.

Actual result:
```
2018-09-25T15:53:11-04:00  INFO    Indexer with 1 processing threads, reader: Rialto::Etl::Readers::NDJsonReader and writer: Rialto::Etl::Writers::SparqlStatementWriter
2018-09-25T15:53:11-04:00 ERROR Unexpected error on record id `` at file position 1
    while executing (to_field @id at lib/rialto/etl/configs/wos_to_sparql_statements.rb:70)
    Exception: TypeError: no implicit conversion of nil into String
    lib/rialto/etl/configs/wos_to_sparql_statements.rb:72:in `digest'

Traceback (most recent call last):
	16: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
	15: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
	14: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
	13: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
	12: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
	11: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
	10: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/thread_pool.rb:110:in `block in maybe_in_thread_pool'
	 9: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer.rb:440:in `block (2 levels) in process'
	 8: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer.rb:339:in `map_to_context!'
	 7: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer.rb:339:in `each'
	 6: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer.rb:345:in `block in map_to_context!'
	 5: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer.rb:367:in `log_mapping_errors'
	 4: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer.rb:346:in `block (2 levels) in map_to_context!'
	 3: from /Users/jlittman/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/traject-2.3.4/lib/traject/indexer/step.rb:142:in `execute'
	 2: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:72:in `block (2 levels) in load_config_file'
	 1: from lib/rialto/etl/configs/wos_to_sparql_statements.rb:72:in `hexdigest'
lib/rialto/etl/configs/wos_to_sparql_statements.rb:72:in `digest': no implicit conversion of nil into String (TypeError)
```

### PR DESCRIPTION
**Pull request by justinlittman**

### CODE REVIEW

File: spec/extractors/web_of_science_spec.rb [hunk 1]
```diff
@@ -44,5 +44,24 @@
...
+
+        allow(extractor.send(:client)).to receive(:page_size).and_return(2)
+      end
+      it 'calls the block on single result' do
+        results = []
+        extractor.each do |records|
+          results << records
+        end
+        # rubocop:disable Lint/PercentStringArray
+        expect(results).to eq %w["one"]
```
Comment (jcoyne) [inline spec/extractors/web_of_science_spec.rb]: May I suggest `expect(results).to eq ['"one"']`?  I think this is more readable.

Comment (justinlittman) [reply spec/extractors/web_of_science_spec.rb]: Agree.

**Comment by justinlittman** [comment]
@jcoyne Fix pushed.
